# Generated by Django 4.2.5 on 2024-02-18 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_No', models.CharField(max_length=100)),
                ('Card_Holdername', models.CharField(max_length=100)),
                ('Expiry_Date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Cartmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tot_Amount', models.CharField(max_length=100)),
                ('Cart_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=100)),
                ('Cat_Desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Fname', models.CharField(max_length=100)),
                ('C_Lname', models.CharField(max_length=100)),
                ('C_House', models.CharField(max_length=100)),
                ('C_City', models.CharField(max_length=100)),
                ('C_Dist', models.CharField(max_length=100)),
                ('C_Pin', models.CharField(max_length=100)),
                ('C_Place', models.CharField(max_length=100)),
                ('C_Phone', models.CharField(max_length=100)),
                ('C_Gender', models.CharField(max_length=100)),
                ('C_DOB', models.CharField(max_length=100)),
                ('C_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flower_Name', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Img', models.ImageField(upload_to='static/flower')),
                ('Type', models.CharField(max_length=100)),
                ('Flower_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Itemmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Desc', models.CharField(max_length=100)),
                ('Item_Cost', models.CharField(max_length=100)),
                ('Item_Img', models.ImageField(upload_to='static/item')),
                ('Stock', models.CharField(max_length=100)),
                ('Profit_Per', models.CharField(max_length=100)),
                ('Item_Status', models.CharField(max_length=100)),
                ('CAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('User_Type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(max_length=100)),
                ('A_Fname', models.CharField(max_length=100)),
                ('A_Lname', models.CharField(max_length=100)),
                ('A_City', models.CharField(max_length=100)),
                ('A_House', models.CharField(max_length=100)),
                ('A_Dist', models.CharField(max_length=100)),
                ('A_Pin', models.CharField(max_length=100)),
                ('A_Place', models.CharField(max_length=100)),
                ('A_Phone', models.CharField(max_length=100)),
                ('Order_Date', models.CharField(max_length=100)),
                ('Order_Total', models.CharField(max_length=100)),
                ('Add_Amt', models.CharField(max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('CARTMAST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_cartmaster')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Fname', models.CharField(max_length=100)),
                ('Staff_Lname', models.CharField(max_length=100)),
                ('Staff_City', models.CharField(max_length=100)),
                ('Staff_House', models.CharField(max_length=100)),
                ('Staff_Dist', models.CharField(max_length=100)),
                ('Staff_Pin', models.CharField(max_length=100)),
                ('Staff_Place', models.CharField(max_length=100)),
                ('Staff_Phone', models.CharField(max_length=100)),
                ('Staff_Gender', models.CharField(max_length=100)),
                ('Staff_Photo', models.ImageField(upload_to='static/staff')),
                ('Staff_DOB', models.CharField(max_length=100)),
                ('Staff_Status', models.CharField(max_length=100)),
                ('USERNAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_login')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_name', models.CharField(max_length=100)),
                ('V_Email', models.CharField(max_length=100)),
                ('V_Dist', models.CharField(max_length=100)),
                ('V_Pin', models.CharField(max_length=100)),
                ('V_Place', models.CharField(max_length=100)),
                ('V_Phone', models.CharField(max_length=100)),
                ('V_Status', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_staff')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Desc', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_customer')),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Purmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pm_Date', models.CharField(max_length=100)),
                ('Tot_Amt', models.CharField(max_length=100)),
                ('Purch_Status', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_staff')),
                ('VENDOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Purchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purch_Quantity', models.CharField(max_length=100)),
                ('Cost_Price', models.CharField(max_length=100)),
                ('Selling_Price', models.CharField(max_length=100)),
                ('Cpurch_Status', models.CharField(max_length=100)),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_itemmaster')),
                ('PM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_purmaster')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Date', models.CharField(max_length=100)),
                ('Payment_Status', models.CharField(max_length=100)),
                ('CARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_card')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Itemchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FLOWER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_flower')),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assign_Date', models.CharField(max_length=100)),
                ('Del_Date', models.CharField(max_length=100)),
                ('Delivery_Status', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_order')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_customer',
            name='USERNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_login'),
        ),
        migrations.AddField(
            model_name='tbl_cartmaster',
            name='CUSTOMER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_customer'),
        ),
        migrations.CreateModel(
            name='tbl_Cartchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='static')),
                ('Cart_Quantity', models.CharField(max_length=100)),
                ('CARTMAST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_cartmaster')),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_itemmaster')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_card',
            name='CUSTOMER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_customer'),
        ),
    ]
