# Generated by Django 4.2.5 on 2024-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0002_cart_child_customization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_child_customization',
            name='Assign_Date',
        ),
        migrations.RemoveField(
            model_name='cart_child_customization',
            name='Del_Date',
        ),
        migrations.RemoveField(
            model_name='cart_child_customization',
            name='Delivery_Status',
        ),
        migrations.AddField(
            model_name='cart_child_customization',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
