# Generated by Django 4.2.5 on 2024-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0003_remove_cart_child_customization_assign_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_order',
            name='Add_Amt',
        ),
        migrations.AddField(
            model_name='cart_child_customization',
            name='Add_Amt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
