# Generated by Django 4.2.5 on 2024-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0004_remove_tbl_order_add_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cartchild',
            name='Cart_Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_itemmaster',
            name='Item_Cost',
            field=models.FloatField(),
        ),
    ]
