# Generated by Django 4.2.5 on 2024-02-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0005_alter_tbl_cartchild_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_delivery',
            name='delivery_boy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
