# Generated by Django 4.2.5 on 2024-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0006_tbl_delivery_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_staff',
            name='Type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
