# Generated by Django 4.2.5 on 2024-02-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0010_remove_tbl_vendor_staff_tbl_vendor_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_purmaster',
            name='STAFF',
        ),
        migrations.AddField(
            model_name='tbl_purmaster',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_login'),
            preserve_default=False,
        ),
    ]
