# Generated by Django 4.2.5 on 2024-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0011_remove_tbl_purmaster_staff_tbl_purmaster_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_purmaster',
            name='Tot_Amt',
            field=models.FloatField(),
        ),
    ]
