# Generated by Django 4.2.5 on 2024-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0012_alter_tbl_purmaster_tot_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cartmaster',
            name='Tot_Amount',
            field=models.FloatField(),
        ),
    ]
