# Generated by Django 4.2.5 on 2024-02-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0013_alter_tbl_cartmaster_tot_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_review',
            name='ITEM',
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_flower_shop_app.tbl_order'),
            preserve_default=False,
        ),
    ]
