# Generated by Django 4.2.5 on 2024-03-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_flower_shop_app', '0014_remove_tbl_review_item_tbl_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_child_customization',
            name='ITEM',
        ),
    ]
